fn main() {
    tauri_build::build();

    // Only build and link the GPR SDK if the vendor directory exists
    let vendor_path = std::path::Path::new("vendor/gpr_sdk");
    if vendor_path.exists() {
        let dst = cmake::Config::new("vendor/gpr_sdk")
            .build_target("all")
            .build();

        // Add search paths for all subdirectories containing the static libraries
        println!(
            "cargo:rustc-link-search=native={}/build/source/lib/gpr_sdk",
            dst.display()
        );
        println!(
            "cargo:rustc-link-search=native={}/build/source/lib/vc5_decoder",
            dst.display()
        );
        println!(
            "cargo:rustc-link-search=native={}/build/source/lib/vc5_common",
            dst.display()
        );
        println!(
            "cargo:rustc-link-search=native={}/build/source/lib/dng_sdk",
            dst.display()
        );
        println!(
            "cargo:rustc-link-search=native={}/build/source/lib/expat_lib",
            dst.display()
        );
        println!(
            "cargo:rustc-link-search=native={}/build/source/lib/tiny_jpeg",
            dst.display()
        );
        println!(
            "cargo:rustc-link-search=native={}/build/source/lib/common",
            dst.display()
        );
        println!(
            "cargo:rustc-link-search=native={}/build/source/lib/xmp_core",
            dst.display()
        );

        // Link all the static libraries generated by the SDK
        println!("cargo:rustc-link-lib=static=gpr_sdk");
        println!("cargo:rustc-link-lib=static=vc5_decoder");
        println!("cargo:rustc-link-lib=static=vc5_common");
        println!("cargo:rustc-link-lib=static=dng_sdk");
        println!("cargo:rustc-link-lib=static=expat_lib");
        println!("cargo:rustc-link-lib=static=tiny_jpeg");
        println!("cargo:rustc-link-lib=static=common");
        println!("cargo:rustc-link-lib=static=xmp_core");

        // Link C++ standard library
        #[cfg(target_os = "macos")]
        println!("cargo:rustc-link-lib=c++");
        #[cfg(target_os = "linux")]
        println!("cargo:rustc-link-lib=stdc++");

        // Tell cargo to invalidate the built crate whenever the wrapper changes
        println!("cargo:rerun-if-changed=vendor/gpr_sdk");
    }
}
