import type { ModifierKey } from '../types';

export const MODIFIER_ORDER: ModifierKey[] = ['Meta', 'Ctrl', 'Alt', 'Shift'];

export const MODIFIER_ALIASES: Record<string, ModifierKey> = {
    cmd: 'Meta',
    command: 'Meta',
    meta: 'Meta',
    ctrl: 'Ctrl',
    control: 'Ctrl',
    alt: 'Alt',
    option: 'Alt',
    shift: 'Shift'
};

export const KEY_CODE_MAP: Record<string, string> = {
    '0': 'Digit0',
    '1': 'Digit1',
    '2': 'Digit2',
    '3': 'Digit3',
    '4': 'Digit4',
    '5': 'Digit5',
    '6': 'Digit6',
    '7': 'Digit7',
    '8': 'Digit8',
    '9': 'Digit9',
    escape: 'Escape',
    esc: 'Escape',
    enter: 'Enter',
    return: 'Enter',
    tab: 'Tab',
    space: 'Space',
    ' ': 'Space',
    backspace: 'Backspace',
    delete: 'Delete',
    del: 'Delete',
    insert: 'Insert',
    ins: 'Insert',
    home: 'Home',
    end: 'End',
    pageup: 'PageUp',
    pagedown: 'PageDown',
    pgup: 'PageUp',
    pgdn: 'PageDown',
    arrowup: 'ArrowUp',
    arrowdown: 'ArrowDown',
    arrowleft: 'ArrowLeft',
    arrowright: 'ArrowRight',
    up: 'ArrowUp',
    down: 'ArrowDown',
    left: 'ArrowLeft',
    right: 'ArrowRight',
    f1: 'F1',
    f2: 'F2',
    f3: 'F3',
    f4: 'F4',
    f5: 'F5',
    f6: 'F6',
    f7: 'F7',
    f8: 'F8',
    f9: 'F9',
    f10: 'F10',
    f11: 'F11',
    f12: 'F12',
    '+': 'Equal',
    '=': 'Equal',
    '-': 'Minus',
    _: 'Minus',
    '[': 'BracketLeft',
    ']': 'BracketRight',
    '{': 'BracketLeft',
    '}': 'BracketRight',
    '\\': 'Backslash',
    '|': 'Backslash',
    ';': 'Semicolon',
    ':': 'Semicolon',
    "'": 'Quote',
    '"': 'Quote',
    ',': 'Comma',
    '<': 'Comma',
    '.': 'Period',
    '>': 'Period',
    '/': 'Slash',
    '?': 'Slash',
    '`': 'Backquote',
    '~': 'Backquote'
};

export const MAC_SYMBOLS: Record<string, string> = {
    Meta: '⌘',
    Ctrl: '⌃',
    Alt: '⌥',
    Shift: '⇧',
    Enter: '↩',
    Backspace: '⌫',
    Delete: '⌦',
    Escape: 'esc',
    Tab: '⇥',
    Space: '␣',
    ArrowUp: '↑',
    ArrowDown: '↓',
    ArrowLeft: '←',
    ArrowRight: '→'
};

export const WINDOWS_SYMBOLS: Record<string, string> = {
    Meta: 'Win',
    Ctrl: 'Ctrl',
    Alt: 'Alt',
    Shift: 'Shift',
    Enter: 'Enter',
    Backspace: 'Backspace',
    Delete: 'Del',
    Escape: 'Esc',
    Tab: 'Tab',
    Space: 'Space',
    ArrowUp: '↑',
    ArrowDown: '↓',
    ArrowLeft: '←',
    ArrowRight: '→'
};
