use crate::core::error::AppResult;
use crate::core::formats::capabilities::ThumbnailCapability;
use crate::core::formats::provider::{FormatProvider, SupportedFormat};
use async_trait::async_trait;
use std::path::Path;
use tracing::instrument;

/// Provider for Comic Book ZIP archives (.cbz).
///
/// Comic Book archives are standard ZIP files containing sequential page
/// images. Thumbnails are generated by extracting the first embedded image.
///
/// # Technical Details
///
/// - **File Format**: ZIP-based comic book container
/// - **Thumbnail**: Extracted from embedded preview images
/// - **Metadata**: Not supported
///
/// # Examples
///
/// ```no_run
/// use mundam_lib::processing::media::providers::archive::comic_book_zip::ComicBookZipProvider;
///
/// let provider = ComicBookZipProvider::new();
/// assert_eq!(provider.supported_formats()[0].extensions, vec!["cbz"]);
/// ```
#[derive(Default)]
pub struct ComicBookZipProvider;

impl ComicBookZipProvider {
    /// Creates a new instance of `ComicBookZipProvider`.
    ///
    /// # Returns
    ///
    /// `ComicBookZipProvider` - A new instance of the provider.
    pub fn new() -> Self {
        Self
    }
}

impl FormatProvider for ComicBookZipProvider {
    /// Returns the unique identifier for this provider.
    ///
    /// # Returns
    ///
    /// `&'static str` - The unique name for this provider.
    fn name(&self) -> &'static str {
        "COMIC_BOOK_ZIP_PROVIDER"
    }

    /// Returns the file extensions supported by this provider.
    ///
    /// # Returns
    ///
    /// `Vec<&'static str>` - The file extensions supported by this provider.
    fn supported_extensions(&self) -> Vec<&'static str> {
        vec!["cbz"]
    }

    /// Returns the detailed format definitions supported by this provider.
    ///
    /// # Returns
    ///
    /// `Vec<SupportedFormat>` - List of supported formats with metadata.
    fn supported_formats(&self) -> Vec<SupportedFormat> {
        use crate::core::formats::types::{
            MediaType, PlaybackStrategy, PreviewStrategy, ThumbnailStrategy,
        };

        vec![SupportedFormat::with_metadata(
            "Comic Book ZIP",
            vec!["cbz"],
            vec!["application/x-cbz"],
            MediaType::Archive,
            ThumbnailStrategy::NativeExtractor,
            PreviewStrategy::NativeExtractor,
            PlaybackStrategy::None,
        )]
    }

    /// Returns the thumbnail generation capability.
    ///
    /// # Returns
    ///
    /// `Option<&dyn ThumbnailCapability>` - The thumbnail generation capability.
    fn thumbnail(&self) -> Option<&dyn ThumbnailCapability> {
        Some(self)
    }
}

#[async_trait]
impl ThumbnailCapability for ComicBookZipProvider {
    /// Generates a thumbnail by extracting the first image from the comic book archive.
    ///
    /// # Arguments
    ///
    /// * `path` - Path to the CBZ archive.
    /// * `_asset_id` - The ID of the asset (unused).
    /// * `size_hint` - The desired dimension for the thumbnail.
    ///
    /// # Errors
    ///
    /// * `AppError::Io` - If the file cannot be read.
    /// * `AppError::Generic` - If no preview is found or decoding fails.
    /// * `AppError::ExtractionProcessTimeout` - If the blocking task times out.
    #[instrument(skip(self, path))]
    async fn generate(&self, path: &Path, _asset_id: &str, size_hint: u32) -> AppResult<Vec<u8>> {
        let path_owned = path.to_path_buf();
        tokio::task::spawn_blocking(move || {
            crate::processing::media::extractors::archive::extract_zip_thumbnail(
                &path_owned,
                size_hint,
            )
        })
        .await
        .map_err(|_| crate::core::error::AppError::ExtractionProcessTimeout)?
    }
}
